### ISSUE TITLE
About Schema definitions

### ISSUE THREAD

**Issue by tpoisseau** [SlimIO/Config#2]
Hello,

I'm interested to use your Config module because of schema validation but I don't found any documentation about how to write theses schema.

https://github.com/SlimIO/Config/blob/v0.7.0/src/config.class.js#L604 seems to be a bit incomplete for writing a detailed schema 😉.

PS :
```bash
npm i @slimio/config
```

is not working. before you publish you should replace by
```bash
npm i git+https://github.com/SlimIO/Config.git#v0.7.0
```

**Comment by fraxken** [comment]
Hi,

Schema follow the latest JSON Schema draft: https://json-schema.org/

Note: Sorry the package was still configured as "private". Now public, so npm install will work :)

Best Regards,
Thomas

**Comment by fraxken** [comment]
For a better schema example, look at:
https://github.com/SlimIO/Config/blob/v0.7.0/test/coreMirror.schema.json
