### ISSUE TITLE
Node process never finish

### ISSUE THREAD

**Issue by tpoisseau** [SlimIO/Config#3]
Hi,

After use this package, I notice that my process never finish and i find in Config constructor a setInteval who never ends

https://github.com/SlimIO/Config/blob/v0.7.0/src/config.class.js#L102

store id and in close method clearInterval.

Can you emit `'close'` event in close method please.

**Comment by fraxken** [comment]
Hi,

Fixed in the latest release v0.9.0. The event "close" has been added as well :) 

Best Regards,
Thomas
